import type { Metadata } from "next";
import { AgentPlayground } from "@/components/agent-playground";
import { Navbar } from "@/components/navbar";
import { ExperienceDuration } from "@/components/experience-duration";
import { portfolio } from "@/content/portfolio";

export const metadata: Metadata = { title: "Elison Felipe — Desenvolvedor Full Stack", description: "Desenvolvedor Full Stack especializado em sistemas com IA, automação e arquitetura de software escalável." };
const Arrow = () => <span aria-hidden="true">↗</span>;
export default function Home() {
  const { projects, skills, experiences, principles, contacts } = portfolio;
  return <main>
    <Navbar />
    <section className="hero shell" id="top"><div className="hero-grid"><div><h1>Software inteligente,<br /><em>feito para funcionar.</em></h1><p className="hero-copy">Desenvolvo produtos com IA que conectam interfaces claras, APIs confiáveis, agentes especializados e fluxos operacionais reais.</p><div className="hero-actions"><a className="button button-primary" href="#work">Conheça o trabalho <Arrow /></a><a className="button button-quiet" href="#contact">Vamos conversar</a></div><div className="hero-meta"><span>Recife, Brasil</span><span>Construindo software há <ExperienceDuration short /></span></div></div><div className="hero-console" aria-label="Resumo do perfil profissional"><div className="console-bar"><span /><span /><span /><p>perfil.profissional</p></div><pre><code>{`const desenvolvedor = {
  atuação: "Full Stack",
  foco: "sistemas com IA",
  desenvolve: ["aplicações com LLM",
    "fluxos de agentes", "automação"],
  status: "em produção"
}`}</code></pre><div className="console-status"><span className="live-dot" /> engenharia orientada à produção</div></div></div></section>
    <section className="metrics shell" aria-label="Métricas selecionadas">{portfolio.metrics.map((item) => <div className="metric" key={item.label}><strong>{item.value}</strong><span>{item.label}</span></div>)}</section>
    <section className="section shell intro" id="about"><div className="section-label">01 / SOBRE</div><div><h2>Do problema à produção, pensando no sistema completo.</h2><p>Atuo na interseção entre produto, engenharia de software e inteligência artificial. O foco não é uma funcionalidade isolada: é um sistema sustentável, com interfaces úteis, arquitetura intencional, validação e espaço para evoluir.</p></div></section>
    <section className="section shell" id="work"><div className="section-heading"><div><div className="section-label">02 / TRABALHOS SELECIONADOS</div><h2>Sistemas com impacto operacional real.</h2></div><p>Os projetos são apresentados no nível arquitetural para preservar informações proprietárias.</p></div><article className="flagship-card"><div className="flagship-copy"><span className="tag">CASE PRINCIPAL / IA CORPORATIVA</span><h3>Ecossistema Inteligente de Operações</h3><p>Um ecossistema completo de capacidades de IA especializadas para fluxos que exigem alto volume de documentos e contexto. Arquitetura e desenvolvimento conduzidos individualmente, da interface à orquestração dos agentes.</p><ul><li>Agentes especializados com camadas determinísticas de validação</li><li>Inteligência documental, transcrição, geração de relatórios, classificação e cálculos</li><li>Dashboards de usabilidade, painel administrativo e integrações entre fluxos</li></ul></div><div className="architecture architecture-flow" aria-label="Diagrama da arquitetura do ecossistema de IA"><div className="architecture-core">ECOSSISTEMA<br />DE IAs</div><div className="architecture-bus" aria-hidden="true" /> <div className="architecture-modules">{["IA Documental", "Transcrição", "Geração de relatórios", "Dashboards de usabilidade", "Painel administrativo", "Agentes jurídicos", "Automação", "Busca e contexto", "Validação"].map((item) => <div className="architecture-node" key={item}>{item}</div>)}</div></div></article><div className="project-grid">{projects.slice(1).map((project) => <article className="project-card" key={project.title}><div><span className="tag">{project.kind}</span><h3>{project.title}</h3><p>{project.description}</p></div><div className="project-stack">{project.stack.map((item) => <span key={item}>{item}</span>)}</div></article>)}</div></section>
    <section className="section shell ecosystem"><div className="section-heading"><div><div className="section-label">03 / PLAYGROUND DE AGENTES</div><h2>Uma visão controlada do fluxo.</h2></div><p>Demonstração sintética — sem modelo real, dados de clientes ou informações confidenciais.</p></div><AgentPlayground /></section>
    <section className="section shell" id="experience"><div className="section-heading"><div><div className="section-label">04 / EXPERIÊNCIA</div><h2>Uma progressão construída na mesma organização.</h2></div><p><ExperienceDuration /> de experiência profissional em tecnologia, calculada a partir de julho de 2024.</p></div><ol className="timeline">{experiences.map((experience) => <li key={experience.role}><div className="timeline-marker" /><div className="timeline-period">{experience.period}</div><div><h3>{experience.role}</h3><p className="company">Queiroz Cavalcanti Advocacia <span>·</span> Recife, Brasil <span>·</span> Híbrido</p><p>{experience.description}</p></div></li>)}</ol></section>
    <section className="section shell" id="stack"><div className="section-heading"><div><div className="section-label">05 / CAPACIDADES</div><h2>Profundidade em toda a superfície do produto.</h2></div><p>Tecnologias organizadas pelos sistemas que ajudam a construir — não uma parede de logos.</p></div><div className="skill-grid">{skills.map((group) => <article className="skill-card" key={group.name}><h3>{group.name}</h3><div>{group.items.map((item) => <span key={item}>{item}</span>)}</div></article>)}</div></section>
    <section className="section shell principles"><div className="section-label">06 / PRINCÍPIOS DE ENGENHARIA</div><div>{principles.map((item, index) => <article key={item.title}><span>0{index + 1}</span><h3>{item.title}</h3><p>{item.description}</p></article>)}</div></section>
    <section className="section shell education"><div><div className="section-label">07 / FORMAÇÃO</div><h2>Aprendizado conectado ao trabalho real.</h2></div><div className="education-list"><article><span>Ensino superior</span><h3>Análise e Desenvolvimento de Sistemas</h3><p>Instituto Federal de Pernambuco — IFPE</p></article><article><span>Formação técnica</span><h3>Redes de Computadores</h3></article><article><span>Aprendizado contínuo</span><h3>20+ certificações em tecnologia</h3><p>Engenharia de IA · Backend · Frontend · DevOps · Cloud · Automação</p></article></div></section>
    <section className="contact shell" id="contact"><div className="section-label">08 / CONTATO</div><h2>Tem um problema que vale a pena resolver?</h2><p>Vamos conversar sobre o sistema por trás dele.</p><div className="contact-links"><a className="button button-primary" href={`mailto:${contacts.email}`}>Enviar e-mail <Arrow /></a><a href={contacts.github} target="_blank" rel="noreferrer">GitHub <Arrow /></a><a href={contacts.linkedin} target="_blank" rel="noreferrer">LinkedIn <Arrow /></a></div></section>
    <footer className="shell"><span>Design e desenvolvimento por Elison Felipe</span><span>© {new Date().getFullYear()} · Next.js + TypeScript</span></footer>
  </main>;
}
